export const HOME_DUMMYONE_BEGIN = 'HOME_DUMMYONE_BEGIN';
export const HOME_DUMMYONE_SUCCESS = 'HOME_DUMMYONE_SUCCESS';
export const HOME_DUMMYONE_FAILURE = 'HOME_DUMMYONE_FAILURE';
export const HOME_DUMMYONE_DISMISS_ERROR = 'HOME_DUMMYONE_DISMISS_ERROR';
