export const SEARCHFILTER_SEARCHCASES_BEGIN = 'SEARCHFILTER_SEARCHCASES_BEGIN';
export const SEARCHFILTER_SEARCHCASES_SUCCESS = 'SEARCHFILTER_SEARCHCASES_SUCCESS';
export const SEARCHFILTER_SEARCHCASES_FAILURE = 'SEARCHFILTER_SEARCHCASES_FAILURE';
export const SEARCHFILTER_SEARCHCASES_DISMISS_ERROR = 'SEARCHFILTER_SEARCHCASES_DISMISS_ERROR';
